version: '3.8'

services:
  # База данных
  db:
    image: postgres:15
    container_name: roulette_db
    restart: always
    environment:
      POSTGRES_DB: roulette_game
      POSTGRES_USER: roulette_user
      POSTGRES_PASSWORD: my_super_secret_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # Бэкенд API
  backend:
    container_name: roulette_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      DB_USER: roulette_user
      DB_HOST: db
      DB_DATABASE: roulette_game
      DB_PASSWORD: my_super_secret_password
      DB_PORT: 5432
      PORT: 3000
    ports:
      - "3001:3000"  # Внешний порт 3001 для nginx proxy

volumes:
  postgres_data: